from views.data_license_setup.ag_grid_data_license import AgGridDataLicense
from views.data_license_setup.form_account import FormAccount
from views.data_license_setup.form_data_license import FormDataLicense
from views.data_license_setup.form_request_system import FormRequestSystem
from views.data_license_setup.accordion_item_request_system import AccordionItemRequestSystem

from views import utils as vu
